In [1]:
import pandas as pd

In [8]:
prices = pd.read_csv("../data/raw/prices.csv", index_col="Date")
prices.index = pd.to_datetime(prices.index)
prices.head()

              AVWS.DE     EIMI.L  IB1T.DE  IUSN.DE     SWRD.L  WMSE.DE
Date
2026-01-02  20.340000  45.980000   7.7060    7.752  47.790001   11.030
2026-01-05  20.695000  46.560001   8.0095    7.894  48.259998   11.198
2026-01-06  20.945000  46.959999   7.9260    7.957  48.312500   11.236
2026-01-07  21.010000  46.799999   7.7930    8.010  48.450001   11.264
2026-01-08  21.129999  46.459999   7.7485    8.044  48.220001   11.164

In [ ]:
returns = prices.pct_change()

             AVWS.DE    EIMI.L   IB1T.DE   IUSN.DE    SWRD.L   WMSE.DE
Date
2026-01-02       NaN       NaN       NaN       NaN       NaN       NaN
2026-01-05  0.017453  0.012614  0.039385  0.018318  0.009835  0.015231
2026-01-06  0.012080  0.008591 -0.010425  0.007981  0.001088  0.003393
2026-01-07  0.003103 -0.003407 -0.016780  0.006661  0.002846  0.002492
2026-01-08  0.005712 -0.007265 -0.005710  0.004245 -0.004747 -0.008878
2026-01-09  0.009229  0.006242  0.011680  0.011934  0.006740  0.011286
2026-01-12  0.002345  0.010909  0.006123  0.000491  0.003914  0.003543
2026-01-13 -0.004678 -0.000423  0.016800 -0.000491 -0.001847  0.009885
2026-01-14  0.008696 -0.000212  0.037159  0.001720 -0.004934 -0.008740
2026-01-15  0.017241  0.010798 -0.002585  0.017047  0.007024  0.016752
2026-01-16 -0.001603 -0.009217 -0.015911  0.000000 -0.002051 -0.001561
2026-01-19 -0.019500  0.005708 -0.020946 -0.013264 -0.010484 -0.010769
2026-01-20 -0.007487 -0.005676 -0.037158 -0.004155 -0.001454 -0.008077
2026-01-21  0.016030  0.008880 -0.012474  0.006627 -0.000832  0.003186
2026-01-22  0.012993  0.010687 -0.006711  0.013288  0.009891  0.001588
2026-01-23 -0.012368 -0.002281  0.010200 -0.010106  0.000000 -0.004933
2026-01-26 -0.009508  0.009975 -0.035667 -0.008629  0.005979  0.001594
2026-01-27 -0.003044  0.013786  0.002856 -0.006375  0.006764  0.008308
2026-01-28 -0.000235  0.004262  0.016542  0.000864 -0.003665  0.001928
2026-01-29  0.002819 -0.007276 -0.057823 -0.007273 -0.007356 -0.009274
2026-01-30  0.000703 -0.007940 -0.010406 -0.001118  0.002779  0.004945
2026-02-02  0.016854 -0.005130 -0.041416  0.011064  0.004824  0.008436
2026-02-03  0.010820  0.011139 -0.031863  0.004795 -0.004392  0.001046
2026-02-04  0.013209 -0.007752 -0.040543  0.002080 -0.001539 -0.021240
2026-02-05 -0.011014 -0.006784 -0.072943 -0.005739 -0.012485 -0.008716
2026-02-06  0.020455  0.013455  0.020711  0.014616  0.012226  0.021353
2026-02-09  0.006236  0.015114 -0.011037  0.005810  0.012027  0.016514
2026-02-10 -0.000664  0.002012  0.001202  0.004934  0.002539 -0.001555
2026-02-11  0.005094  0.007028 -0.042785 -0.002036 -0.001722  0.003981
2026-02-12 -0.008594 -0.004187 -0.000179 -0.009960 -0.009439 -0.008621
2026-02-13  0.006668 -0.000601  0.042645  0.006061 -0.001895 -0.004000
2026-02-16  0.001987  0.002605 -0.020278 -0.001205 -0.003028  0.001222
2026-02-17 -0.005289 -0.003997  0.005876  0.001086 -0.000412  0.003313
2026-02-18  0.015064  0.012440 -0.010986  0.012291  0.010301  0.016687
2026-02-19 -0.004583 -0.007333 -0.006700 -0.003095 -0.006321 -0.007523
2026-02-20 -0.000219  0.014973  0.015355  0.003343  0.005233  0.009991
2026-02-23 -0.010746 -0.002950 -0.031206 -0.011544 -0.005410 -0.005117
2026-02-24  0.005542  0.014993 -0.023640  0.007585  0.002874  0.009601
2026-02-25  0.003527  0.007191  0.063580  0.003585  0.009415  0.007641
2026-02-26  0.003954 -0.008491 -0.012686  0.003810 -0.002636 -0.011291
2026-02-27 -0.006127 -0.002336 -0.018217 -0.002965 -0.002338 -0.003579
2026-03-02  0.004183 -0.021849  0.062657  0.000476 -0.009373 -0.000513
2026-03-03 -0.012717 -0.054846 -0.005483 -0.016528 -0.019233 -0.023276
2026-03-04  0.009105  0.018991  0.065479  0.009431  0.014943  0.017698
2026-03-05 -0.010123 -0.024022 -0.021095 -0.008145 -0.010384 -0.013258
2026-03-06 -0.021565  0.000000       NaN       NaN -0.008248 -0.011865
2026-03-09 -0.015905 -0.000424       NaN       NaN -0.005369 -0.003532
2026-03-10  0.024244  0.032053       NaN       NaN  0.017887  0.022683
2026-03-11 -0.009693 -0.013780       NaN       NaN -0.011022 -0.002599
2026-03-12 -0.005463 -0.023566       NaN       NaN -0.007886 -0.008165
2026-03-13 -0.003204 -0.004699       NaN       NaN -0.008372 -0.002627

In [11]:
returns.dropna()

             AVWS.DE    EIMI.L   IB1T.DE   IUSN.DE    SWRD.L   WMSE.DE
Date
2026-01-05  0.017453  0.012614  0.039385  0.018318  0.009835  0.015231
2026-01-06  0.012080  0.008591 -0.010425  0.007981  0.001088  0.003393
2026-01-07  0.003103 -0.003407 -0.016780  0.006661  0.002846  0.002492
2026-01-08  0.005712 -0.007265 -0.005710  0.004245 -0.004747 -0.008878
2026-01-09  0.009229  0.006242  0.011680  0.011934  0.006740  0.011286
2026-01-12  0.002345  0.010909  0.006123  0.000491  0.003914  0.003543
2026-01-13 -0.004678 -0.000423  0.016800 -0.000491 -0.001847  0.009885
2026-01-14  0.008696 -0.000212  0.037159  0.001720 -0.004934 -0.008740
2026-01-15  0.017241  0.010798 -0.002585  0.017047  0.007024  0.016752
2026-01-16 -0.001603 -0.009217 -0.015911  0.000000 -0.002051 -0.001561
2026-01-19 -0.019500  0.005708 -0.020946 -0.013264 -0.010484 -0.010769
2026-01-20 -0.007487 -0.005676 -0.037158 -0.004155 -0.001454 -0.008077
2026-01-21  0.016030  0.008880 -0.012474  0.006627 -0.000832  0.003186
2026-01-22  0.012993  0.010687 -0.006711  0.013288  0.009891  0.001588
2026-01-23 -0.012368 -0.002281  0.010200 -0.010106  0.000000 -0.004933
2026-01-26 -0.009508  0.009975 -0.035667 -0.008629  0.005979  0.001594
2026-01-27 -0.003044  0.013786  0.002856 -0.006375  0.006764  0.008308
2026-01-28 -0.000235  0.004262  0.016542  0.000864 -0.003665  0.001928
2026-01-29  0.002819 -0.007276 -0.057823 -0.007273 -0.007356 -0.009274
2026-01-30  0.000703 -0.007940 -0.010406 -0.001118  0.002779  0.004945
2026-02-02  0.016854 -0.005130 -0.041416  0.011064  0.004824  0.008436
2026-02-03  0.010820  0.011139 -0.031863  0.004795 -0.004392  0.001046
2026-02-04  0.013209 -0.007752 -0.040543  0.002080 -0.001539 -0.021240
2026-02-05 -0.011014 -0.006784 -0.072943 -0.005739 -0.012485 -0.008716
2026-02-06  0.020455  0.013455  0.020711  0.014616  0.012226  0.021353
2026-02-09  0.006236  0.015114 -0.011037  0.005810  0.012027  0.016514
2026-02-10 -0.000664  0.002012  0.001202  0.004934  0.002539 -0.001555
2026-02-11  0.005094  0.007028 -0.042785 -0.002036 -0.001722  0.003981
2026-02-12 -0.008594 -0.004187 -0.000179 -0.009960 -0.009439 -0.008621
2026-02-13  0.006668 -0.000601  0.042645  0.006061 -0.001895 -0.004000
2026-02-16  0.001987  0.002605 -0.020278 -0.001205 -0.003028  0.001222
2026-02-17 -0.005289 -0.003997  0.005876  0.001086 -0.000412  0.003313
2026-02-18  0.015064  0.012440 -0.010986  0.012291  0.010301  0.016687
2026-02-19 -0.004583 -0.007333 -0.006700 -0.003095 -0.006321 -0.007523
2026-02-20 -0.000219  0.014973  0.015355  0.003343  0.005233  0.009991
2026-02-23 -0.010746 -0.002950 -0.031206 -0.011544 -0.005410 -0.005117
2026-02-24  0.005542  0.014993 -0.023640  0.007585  0.002874  0.009601
2026-02-25  0.003527  0.007191  0.063580  0.003585  0.009415  0.007641
2026-02-26  0.003954 -0.008491 -0.012686  0.003810 -0.002636 -0.011291
2026-02-27 -0.006127 -0.002336 -0.018217 -0.002965 -0.002338 -0.003579
2026-03-02  0.004183 -0.021849  0.062657  0.000476 -0.009373 -0.000513
2026-03-03 -0.012717 -0.054846 -0.005483 -0.016528 -0.019233 -0.023276
2026-03-04  0.009105  0.018991  0.065479  0.009431  0.014943  0.017698
2026-03-05 -0.010123 -0.024022 -0.021095 -0.008145 -0.010384 -0.013258

In [12]:
portfolio = pd.read_csv("../data/portfolio.csv")
portfolio

    ticker  weight
0   SWRD.L    0.38
1   EIMI.L    0.22
2  IUSN.DE    0.12
3  AVWS.DE    0.06
4  WMSE.DE    0.08
5  IB1T.DE    0.04

In [13]:
weights = dict(zip(portfolio.ticker, portfolio.weight))
weights

{'SWRD.L': 0.38,
 'EIMI.L': 0.22,
 'IUSN.DE': 0.12,
 'AVWS.DE': 0.06,
 'WMSE.DE': 0.08,
 'IB1T.DE': 0.04}

In [18]:
returns = returns[portfolio.ticker]
portfolio_returns = returns.mul(portfolio.weight.values, axis=1).sum(axis=1)
portfolio_returns.head()

Date
2026-01-02    0.000000
2026-01-05    0.012552
2026-01-06    0.003840
2026-01-07    0.000846
2026-01-08   -0.003489
dtype: float64

In [19]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'